modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "cobblemonxeiplugin"
version = "${version}"
displayName = "Cobblemon XEI Plugin"
authors = "iouter"
description = '''
display the cobblemon's information.
'''
#logoFile = ""

[[dependencies.cobblemonxeiplugin]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonxeiplugin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonxeiplugin]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemonxeiplugin]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.4,)"
ordering = "AFTER"
side = "BOTH"